version: '3.8'

services:
  bot:
    build: .
    container_name: ai-bot
    restart: always
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - BITRIX24_WEBHOOK=${BITRIX24_WEBHOOK}
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ai_bot_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: