version: "3.8"

services:
  db:
    build:
      context: ./backend
      dockerfile: Dockerfile.db
    container_name: ai_chat_db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: ai_chat
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ai_chat_backend
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL_WEB: postgresql://admin:admin@db:5432/ai_chat
      BITRIX24_WEBHOOK: your-bitrix-webhook
      OPENAI_API_KEY: your-chat-api-key

  frontend:
    build:
      context: ./chat-app
      dockerfile: Dockerfile
    container_name: ai_chat_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  pgdata:
